###1. Get all cinemrooms
GET http://localhost:5005/api/v1/cinemarooms

###2. Get cinemroom by ID
GET http://localhost:5005/api/v1/cinemarooms/5fa93fe12423434148645470

###3. POST
POST http://localhost:5005/api/v1/cinemarooms
content-type: application/json

{
    "name": "Stockholm Hall",
    "ticketPrice": 20,
    "city": "Stockholm",
    "seats": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],
    "takenSeats": [5,4,13,22,25]
}

###3.b POST
POST http://localhost:5005/api/v1/cinemarooms
content-type: application/json

{
    "name": "Hallonberg Hall",
    "ticketPrice": 15,
    "city": "Stockholm",
    "seats": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],
    "takenSeats": [2,14,20,23,25]
}



###5. DELETE cinemroom by ID
DELETE http://localhost:5005/api/v1/cinemarooms/5fa93fe12423434148645470