#### 2. Get ALL movies:
GET http://localhost:5005/api/v1/movies


### 3. GET movie by ID: 
GET http://localhost:5005/api/v1/movies/5fa6fdaf99169350dc3744ad

### 4. Update(PATCH) movie by ID:
PATCH http://localhost:5005/api/v1/movies/5fa6fdaf99169350dc3744ad
content-type: application/json

{
    "popularity": 118
}


### 5. DELETE movie by ID  
DELETE http://localhost:5005/api/v1/movies/5fab41ee2979a10310800b81
