#### 2. Get ALL movies:
GET http://localhost:5005/api/v1/movies


### 3. GET movie by ID: 
GET http://localhost:5005/api/v1/movies/5fb04b2892852c59b0bc1e90

### 4. Update(PATCH) movie by ID:
PATCH http://localhost:5005/api/v1/movies/5fb04b2892852c59b0bc1e90
content-type: application/json

{
    "popularity": 118
}


### 5. DELETE movie by ID  
DELETE http://localhost:5005/api/v1/movies/5fb04b2892852c59b0bc1e90