GET http://localhost:5005/api/v1/movies/
#### 2. Get ALL reservations:
GET http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/


### 3. GET reservations from showtime: 
GET http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations 

### 
GET http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations/5fb04fc1a0ec6e0cdc4891e6

### 4a POST reservation
POST http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations
content-type: application/json

{
    "username": "ticket buyer",
    "email": "buyermail123@gmail.com",
    "isPaymentSucceed": true,
    "seats": [19,20],
    "totalPrice": 40,
    "notes": "movie title can be here",
    "showtime": "5fb04d5da0ec6e0cdc4891e1"

}

### 4b POST reservation
POST http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations
content-type: application/json

{
    "username": "ticket buyer second2",
    "email": "secondbuyermail123@gmail.com",
    "isPaymentSucceed": false,
    "seats": [1],
    "totalPrice": 20,
    "notes": "movie title can be here2",
    "showtime": "5fb04d5da0ec6e0cdc4891e1"

}

### 5. Update(PATCH) reservations by ID:
PATCH http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations/5fb04fc1a0ec6e0cdc4891e6
content-type: application/json

{
    "username": "ticket buyer second",
    "email": "secondbuyermail123@gmail.com",
    "isPaymentSucceed": true,
    "seats": [1],
    "totalPrice": 20,
    "notes": "movie title can be here2"

}


### 5. DELETE reservations by ID  
DELETE http://localhost:5005/api/v1/movies/5fb020cc92852c59b0bc1e85/showtimes/5fb04d5da0ec6e0cdc4891e1/reservations/5fb050b4a0ec6e0cdc4891e7
