@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1
@MOVIE_ID=5fc51c025a11b6195ccfcd66
@SHOW_TIME_ID=5fc51c4b5a11b6195ccfcd6d
@DATE1=2021-12-13
@DATE2=2021-12-20
@DATE3=2021-12-30

### GET all showtimes
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/

### GET showtime with :id 
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/{{SHOW_TIME_ID}} 
 
### POST showtime DATE 1-mor
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE1}}T12:30:00.000Z",
    "endAt": "{{DATE1}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 1-aft
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE1}}T16:30:00.000Z",
    "endAt": "{{DATE1}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [3,7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 1-eve
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE1}}T20:30:00.000Z",
    "endAt": "{{DATE1}}T22:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [15,16],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}


### POST showtime DATE 2-mor
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE2}}T12:30:00.000Z",
    "endAt": "{{DATE2}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 2-aft
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE2}}T16:30:00.000Z",
    "endAt": "{{DATE2}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [3,7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 2-eve
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE2}}T20:30:00.000Z",
    "endAt": "{{DATE2}}T22:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [1],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

 

### POST showtime DATE 3-mor
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE3}}T12:30:00.000Z",
    "endAt": "{{DATE3}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 3-aft
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE3}}T16:30:00.000Z",
    "endAt": "{{DATE3}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [3,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime DATE 3-eve
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE3}}T20:30:00.000Z",
    "endAt": "{{DATE3}}T22:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [15,16],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}



















