@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1
@MOVIE_ID=5fc51c025a11b6195ccfcd66
@SHOW_TIME_ID=5ff7969b588ad13f00201f31
@DATE=2021-01-07
@DATE_PAST=2020-12-07
### GET all showtimes
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/

### GET showtime with :id 
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/{{SHOW_TIME_ID}} 
 
### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T12:30:00.000Z",
    "endAt": "{{DATE}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T12:30:00.000Z",
    "endAt": "{{DATE}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [3,7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

###3.b POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T16:30:00.000Z",
    "endAt": "{{DATE}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [15],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}


###3.b POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T16:30:00.000Z",
    "endAt": "{{DATE}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [15],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T20:00:00.000Z",
    "endAt": "{{DATE}}T22:00:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [1,5,25],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE}}T20:00:00.000Z",
    "endAt": "{{DATE}}T22:00:00.000Z",
    "hallName": "Solna Cinema Hall",
    "unavailableSeats": [1,5,25],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}


###### inThePAST START #########

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE_PAST}}T12:30:00.000Z",
    "endAt": "{{DATE_PAST}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE_PAST}}T12:30:00.000Z",
    "endAt": "{{DATE_PAST}}T14:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [3,7,22],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

### POST showtime
POST {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes
content-type: application/json

{
    "startAt": "{{DATE_PAST}}T16:30:00.000Z",
    "endAt": "{{DATE_PAST}}T18:30:00.000Z",
    "hallName": "Stockholm Cinema Hall",
    "unavailableSeats": [15,17],
    "city": "Stockholm",
    "movie": "{{MOVIE_ID}}"
}

###### inThePAST END #########
 
 
 




















