###1. Get all showtime
GET http://localhost:5005/api/v1/showtime

###2. Get showtime by ID
GET http://localhost:5005/api/v1/showtime/5fa92ea4b9773101fcc5d933

###3.a POST showtime
POST http://localhost:5005/api/v1/showtime
content-type: application/json

{
    "startDate": "2020-12-01",
    "startAt": "12:30",
    "endAt": "2020-12-01",
    "movieId": "5fa6f46899169350dc3744a5",
    "cinemaRoomId": "5fa880c6dded804a54cadb75"
}

###3.b POST showtime
POST http://localhost:5005/api/v1/showtime
content-type: application/json

{
    "startDate": "2020-12-02",
    "startAt": "14:30",
    "endAt": "2020-12-02",
    "movieId": "5fa6f46899169350dc3744a5",
    "cinemaRoomId": "5fa880c6dded804a54cadb75"
}

####3.c
POST http://localhost:5005/api/v1/showtime
content-type: application/json

{
    "startDate": "2020-12-04",
    "startAt": "15:30",
    "endAt": "2020-12-04",
    "movieId": "5fa6f46899169350dc3744a5",
    "cinemaRoomId": "5fa880c6dded804a54cadb75"
}

###3.d POST showtime
POST http://localhost:5005/api/v1/showtime
content-type: application/json

{
    "startDate": "2020-12-05",
    "startAt": "21:30",
    "endAt": "2020-12-05",
    "movieId": "5fa6f46899169350dc3744a5",
    "cinemaRoomId": "5fa880c6dded804a54cadb75"
}


###5. DELETE showtime by ID
DELETE http://localhost:5005/api/v1/showtime/5fa92aea46d63857f41c0402