@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1
@MOVIE_ID=5fc51c025a11b6195ccfcd66
@SHOW_TIME_ID=5fc51c4b5a11b6195ccfcd6d
 
### GET all showtimes
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/

### GET showtime with :id 
GET {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/{{SHOW_TIME_ID}} 

### PATCH showtime with :id 
PATCH {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/{{SHOW_TIME_ID}} 
content-type: application/json

{
 
    "hallName": "Sollentuna Cinema Hall"  
    
}

### DELETE showtime with :id 
DELETE {{BASE_URL}}/movies/{{MOVIE_ID}}/showtimes/{{SHOW_TIME_ID}} 